SELECT * FROM customer_data limit 10;
-- Q1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) 
from customer_data 
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_data 
where discount_applied = 'Yes' and purchase_amount > 
(select avg(purchase_amount) from customer_data)

-- Q3. Which are the top 5 product with highest average review rating?
select item_purchased, AVG(review_rating) as Avg_product_rating 
from customer_data
group by item_purchased
order by AVG(review_rating) DESC
LIMIT 5 

-- Q4. compare the average purchase amount between standard and express shipping.
select shipping_type,
AVG(purchase_amount)
from customer_data
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? compare avg spend and total revenue bw subscriber and non-subscriber?
select subscription_status,
count(customer_id) as Total_customer,
avg(purchase_amount),
sum(purchase_amount) 
from customer_data
where subscription_status in ('Yes', 'NO')
group by subscription_status

-- Q6. Which 5 products have the highest percentage of purchases with the discount applied?
select item_purchased,	
ROUND(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate DESC
limit 5

-- Q7. segment customers into New, returning, and loyal based on their total 
-- number of previous purchases and show the count of each segment.

with customer_type as(
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer_data
)
select customer_segment, count(*) as Number_of_customer 
from customer_type
group by customer_segment 

-- Q8. What are the top 3 most purchased product within each category?

with item_count as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) DESC) as item_rank
from customer_data
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (More than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group ?

select age_group,
sum(purchase_amount) as Total_revenue
from customer_data
group by age_group
order by Total_revenue DESC;

